spring:
  application:
    name: user
  datasource:
    url: jdbc:postgresql://localhost:5435/ms-user-ms
    username: postgres-user
    password: postgres-password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


  rabbitmq:
    addresses: ${MQ_ADDRESS}
    username: ${MQ_USER}
    password: ${MQ_PASSWORD}
    virtual-host: ${MQ_USER}
    ssl:
      enabled: true
    template:
      exchange: app-exchange
      routing-key: email.welcome

server:
  port: 8082

api:
  security:
    token:
      secret: ${SECRET}
